stages:
    - build
    - deploy

default:
    image: docker:latest
    services:
        - docker:dind 
        
variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: "" 

build_Docker_job:
    stage: build
    tags:
        - VM-Azure
    before_script:
        - docker version
    script:
        - echo "Building the project"
        - docker login registry.gitlab.com -u ijerishweta -p $TOKEN
        - docker build -t registry.gitlab.com/devops_ci-cd2/myfirstgitlab_cicd .
        - docker push registry.gitlab.com/devops_ci-cd2/myfirstgitlab_cicd
    artifacts:
        paths:
            - $CI_PROJECT_DIR/
        exclude:
            - Dockerfile

pages:
    stage: deploy
    tags:
        - VM-Azure
    script:
        - mkdir public
        - cp *.html public/
    artifacts:
        paths:
             - public
